// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Codescene.VSExtension.VS2022
{
    internal sealed partial class Vsix
    {
        public const string Id = "ReeinventVSPluginTest.c90b6097-3fbd-4b82-a308-f9568074c67a";
        public const string Name = "Reeinvent VS plugin test";
        public const string Description = @"Developing and testing first Visual studio extensionDevelop";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Emir Prljaca";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
