// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Codescene.VSExtension.VS2022
{
    internal sealed partial class Vsix
    {
        public const string Id = "CodeScene.c90b6097-3fbd-4b82-a308-f9568074c67a";
        public const string Name = "CodeScene";
        public const string Description = @"Integrates CodeScene analysis into Visual Studio. Keeps your code clean and maintainable.";
        public const string Language = "en-US";
        public const string Version = "0.1.3";
        public const string Author = "CodeScene";
        public const string Tags = "ai, ai code review, code analysis, code health, code metrics, code review, code quality, technical debt";
        public const bool IsPreview = false;
    }
}
