// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Codescene.VSExtension.VS2022
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string CodesceneExtensionString = "68d6a325-11e8-4790-a4ba-0edd001fb080";
        public static Guid CodesceneExtension = new Guid(CodesceneExtensionString);

        public const string CodeSceneCmdSetString = "db0701cc-1e44-41f7-97d6-29b160a70bcb";
        public static Guid CodeSceneCmdSet = new Guid(CodeSceneCmdSetString);

        public const string guidSHLMainMenuString = "d309f791-903f-11d0-9efc-00a0c911004f";
        public static Guid guidSHLMainMenu = new Guid(guidSHLMainMenuString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CodeSceneOuterGroup = 0x1020;
        public const int CodeSceneMenu = 0x1021;
        public const int CodeSceneCommandsGroup = 0x1022;
        public const int OpenSettings = 0x1025;
        public const int CopyDeviceId = 0x1026;
        public const int SignInCommand = 0x0400;
        public const int OpenStatusWindowCommand = 0x0800;
        public const int SignOutCommand = 0x0500;
        public const int IDM_VS_MENU_EXTENSIONS = 0x0091;
    }
}
