// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodesceneReeinventTest
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string Package = "68D6A325-11E8-4790-A4BA-0EDD001FB080";
        public const string PackageActivation = "063BA845-A14B-40A1-97B7-33BFD00272E2";
        public const string CodeSceneMenuCommandSet = "DB0701CC-1E44-41F7-97D6-29B160A70BCB";
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CodesceneMenuGroup = 0x0001;
        public const int CodesceneMenuGroupEdit = 0x0002;
        public const int OpenCodesceneSiteCommand = 0x0400;
        public const int OpenStatusWindowCommand = 0x0800;
        public const int OptionsCommand = 0x1025;

    }
}