name: Publish latest VSIX release (manual)

on:
  workflow_dispatch:
    inputs:
      publish_vs_marketplace:
        type: boolean
        default: true
        description: Publish to Visual Studio Marketplace

jobs:
  publish:
    name: 'Publish VSIX Extension'
    runs-on: windows-latest

    steps:
      - name: Get latest release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          regex: true
          file: '.*\.vsix'
          version: 'latest'
          target: './'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Output file-name for use in publishing steps
        id: latest-release
        run: echo "file-name=$(Get-ChildItem *.vsix | Select-Object -First 1).FullName" >> $env:GITHUB_OUTPUT

      - name: Publish to Visual Studio Marketplace
        if: ${{ github.event.inputs.publish_vs_marketplace == 'true' }}
        run: >
          "C:\Program Files (x86)\Microsoft Visual Studio\2022\Professional\VSSDK\VisualStudioIntegration\Tools\Bin\VsixPublisher.exe"
          publish
          -payload ${{ steps.latest-release.outputs.file-name }}
          -publishManifest publishManifest.json
          -personalAccessToken ${{ secrets.VISUAL_STUDIO_MARKETPLACE_PUBLISHING_TOKEN }}
