name: Publish latest VSIX release (manual)

on:
  workflow_dispatch:
    inputs:
      publish_vs_marketplace:
        type: boolean
        default: true
        description: Publish to Visual Studio Marketplace

jobs:
  # ------------------------
  # Job 1: Verify VSIX
  # ------------------------
  verify:
    name: Verify VSIX package
    runs-on: windows-latest
    steps:
      - name: Get latest release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          regex: true
          file: '.*\.vsix'
          version: 'latest'
          target: './'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Output file-name for use in publishing steps
        id: latest-release
        shell: pwsh
        run: |
          $file = (Get-ChildItem *.vsix | Select-Object -First 1).FullName
          echo "file-name=$file" >> $env:GITHUB_OUTPUT

      - name: Find VsixPublisher.exe
        id: find-vsixpub
        shell: pwsh
        run: |
          $vsix = Get-ChildItem "C:\Program Files\Microsoft Visual Studio\2022" -Recurse -Filter VsixPublisher.exe -ErrorAction SilentlyContinue | 
                  Select-Object -First 1 -ExpandProperty FullName
          if (-not $vsix) { throw "VsixPublisher.exe not found on runner." }
          echo "path=$vsix" >> $env:GITHUB_OUTPUT

      - name: Verify VSIX (dry run)
        shell: pwsh
        run: |
          & "${{ steps.find-vsixpub.outputs.path }}" verify `
            -payload "${{ steps.latest-release.outputs.file-name }}" `
            -publishManifest publishManifest.json

      - name: Upload VSIX artifact (for publish job)
        uses: actions/upload-artifact@v4
        with:
          name: vsix-package
          path: '*.vsix'

  # ------------------------
  # Job 2: Publish VSIX
  # ------------------------
  publish:
    name: Publish VSIX Extension
    runs-on: windows-latest
    needs: verify
    if: ${{ github.event.inputs.publish_vs_marketplace == 'true' }}
    steps:
      - name: Download VSIX artifact
        uses: actions/download-artifact@v4
        with:
          name: vsix-package
          path: .

      - name: Find VsixPublisher.exe
        id: find-vsixpub
        shell: pwsh
        run: |
          $vsix = Get-ChildItem "C:\Program Files\Microsoft Visual Studio\2022" -Recurse -Filter VsixPublisher.exe -ErrorAction SilentlyContinue | 
                  Select-Object -First 1 -ExpandProperty FullName
          if (-not $vsix) { throw "VsixPublisher.exe not found on runner." }
          echo "path=$vsix" >> $env:GITHUB_OUTPUT

      - name: Publish to Visual Studio Marketplace
        shell: pwsh
        run: |
          $file = (Get-ChildItem *.vsix | Select-Object -First 1).FullName
          & "${{ steps.find-vsixpub.outputs.path }}" publish `
            -payload "$file" `
            -publishManifest publishManifest.json `
            -personalAccessToken "${{ secrets.VISUAL_STUDIO_MARKETPLACE_PUBLISHING_TOKEN }}"
